#!/bin/bash
if [ $# !=10 ]; then
    printLog "参数不合法,程序将退出"
    exit 0
fi
username=$1
password=$2
mamachinesListFile=$3
cookieFile=$4
loginURL=$5
detailURLPrefix=$6
orderURLPrefix=$7
logFile=$8
loopFile=$9
#低于该门限值的,检测前不登录
shift
threshold=$9
#租期
shift
tenancy=$9
#系统最大租期
shift
maxTenancy=$9

#nohup sh ./${app} ${username} ${password} ${mamachinesListFile} ${cookieFile}  ${loginURL}  ${detailURLPrefix}  ${orderURLPrefix}  ${logfile} ${loopFile} ${threshold} >${monitorLog} 2>&1 &
function printLog()
{
	local dateStr=`date "+%Y-%m-%d %H:%M:%S"`
	if [ ! -f ${loginFile} ]; then
		:>${loginFile}
	fi
	echo "[${dateStr}] $@">>${logFile}
}

if [ ! -f ${loginFile} ]; then
    :>${loginFile}
fi
truncate ${loginFile} --size=0
echo -n 1 > ${loopFile}

printLog "启动服务"

#请求之前是否需要登录:高频请求不需要总是登录
loginOption=1

while [ `cat ${loopFile}` -eq 1 ];
do
	if [ ${loginOption} -eq 1 ]; then
		curl -F "username=${username}" -F "password=${password}" --cookie-jar ${cookieFile} ${loginURL} > /dev/null
		if [ $? -eq 0 ]; then
			printLog "登录成功"
		else
			printLog "登录失败"
			exit 1
		fi
	fi

	minDiff=$(( 3600 * 24 * ${tenancy} ))
	machinesList="`cat ${mamachinesListFile}`"
	for eachMachine in ${machinesList[@]}
	do
	    detailURL="${detailURLPrefix}${eachMachine}"
	    rs=`curl -b ${cookieFile} ${detailURL}`
	    wait
	    if [[ ${rs} =~ "使用人" ]]; then
			startTimeStr=`echo "${rs}" | grep -E  '[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}' -o`
			lease=`echo "${rs}" | grep -E  '[0-9]{2} 天' -o | grep -E '[0-9]{2}' -o`
			secondsA=`date -d "${startTimeStr}" +%s`
			deadline=`expr ${secondsA} + $(( 3600 * 24 * ${tenancy} ))`
			secondsNow=`date +%s`
			diffSeconds=$(( ${deadline} - ${secondsNow} ))
			if [ ${diffSeconds} -lt ${minDiff} ] && [ ${diffSeconds} -gt 0 ]; then
				minDiff=${diffSeconds}
			fi
			if [ ${diffSeconds} -lt 0 ]; then
				printLog "警告:${eachMachine}可能被长期占有,请确认!"
			else
				printLog "${eachMachine}正在租期内,将在$(( ${diffSeconds} / ( 24 * 3600) ))天$(( ${diffSeconds} % ( 24 * 3600) / 3600 ))时$(( ${diffSeconds} % 3600 / 60 ))分$(( ${diffSeconds} % 60 ))秒后到期"
			fi
	    elif [[ ${rs} =~ "申请使用" ]]; then
			orderURL="${orderURLPrefix}${eachMachine}"
			#默认按最大租期续租
			curl -F "sel_num=${maxTenancy}" -b ${cookieFile} ${orderURL} > /dev/null
			if [ $? -eq 0 ]; then
				printLog "预定${eachMachine}成功"
			else
				printLog "预定${eachMachine}失败"
			fi
		else 
			printLog "未知错误:${rs}"
	    fi
	done
	
	sleepTime=$(( ${minDiff} / 60 + 1))
	printLog "将在${sleepTime}($(( ${sleepTime} / ( 24 * 3600) ))天$(( ${sleepTime} % ( 24 * 3600) / 3600 ))时$(( ${sleepTime} % 3600 / 60 ))分$(( ${sleepTime} % 60 )))秒后再次检测"

	if [ ${sleepTime} -gt ${threshold} ];then
		loginOption=1		
	else
		printLog "进入频繁刷新时期,切换到直接请求模式" 
		loginOption=0
	fi
	sleep ${sleepTime}
done



